### ISSUE TITLE
File exclusion doesn't work

### ISSUE THREAD

**Issue by maksimf** [SublimeLinter/SublimeLinter-rubocop#20]
I have `.rubocop.yml`:
```yml
AllCops:
  RunRailsCops: true
  Exclude:
    - db/schema.rb
Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 20
```
And so I expect linter to ignore `db/schema.rb` which it doesn't. I asked guys from rubocop and [they told me](https://github.com/bbatsov/rubocop/issues/893#issuecomment-95591705) that I need to specify `--force-exclusion` flag to make linter work, which i did in my `SublimeLinter.sublime-settings`:
```json
"linters": {
    "rubocop": {
        "@disable": false,
        "args": [
            "--force-exclusion"
        ],
        "excludes": []
    }
}
```
But this doesn't work. I ran linter in debug mode and figured out that it uses the following command: `/usr/local/opt/rbenv/shims/ruby -S rubocop --force-exclusion --config=/Users/m.filippov/myproject/.rubocop.yml db/schema.rb`
And when I run this command in console manually, then everything works just fine, schema.rb is skipped. Do you have any idea what can be wrong?

**Comment by reconbot** [comment]
We lose the directory part of the file's path when we send it to rubocop. SublimeLinter does this to support unsaved files. I've been exploring a patch to use in our linter to recreate the directories in `tmp` for the very related #10 about railscops.

**Comment by maksimf** [comment]
Should this config work then?
```yml
AllCops:
  RunRailsCops: true
  Exclude:
    - schema.rb
Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 20
```
