### ISSUE TITLE
Linter not ignoring directories listed in `.rubocop.yml`?

### ISSUE THREAD

**Issue by kreeger** [SublimeLinter/SublimeLinter-rubocop#8]
I've got a `.rubocop.yml` file with this bit at the top:

``` yaml
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
```

But the plugin doesn't seem to be taking these exclusions into account. Is there a different way to exclude files and directories from being linted? Perhaps through SublimeLinter's settings itself?
